### PR TITLE
setup `DATABASE_HOST`

### PR DESCRIPTION
**Pull request by no-reply**
init scripts require a database host. ensure one exists regardless of source.

the hyrax chart overrides this by providing it in the secrets file. i think this
will work, but i still can't deploy Hyrax against this published, so we can
cross that bridge when we come to it.

i'm able to deploy the chart standalone after reverting to 0.5.1 and adding this.

@orangewolf: what should be our next steps to getting Hyrax running on this chart?

### CODE REVIEW

**Comment by no-reply** [comment]
after a rebase, i think the only reason for the need to revert is `Error: create: failed to create: Request entity too large: limit is 3145728`. i think this is because of the several `.gz` files now in the chart's directory.

**Comment by no-reply** [comment]
confirming that i can deploy from this if i do `rm *.tgz`.

i think we just need to restructure this so chart packages and the index aren't in the chart's path--or otherwise get a new publishing strategy.

**Comment by orangewolf** [comment]
@no-reply you can see from the commits that I was fighting these variables hard yesterday. I think the scoping is a good idea, and I'm fine with moving username back under the namespace and updating my configs. However, i'd like to go a step further and support setting the postgreshost explicitly to allow this chart to support upstream postgresql hosts or external dbs and this code disables that as it stands.

this is my first chart and the docs are _sparce_ I'm sure we can restructre it to fix the file issue.

**Comment by no-reply** [comment]
sounds good.

the hyrax chart is cheating a bit to provide `DATABASE_HOST` in the passthrough secret (i still think this is an awkward pattern, and am looking for a replacement). adding `postgresql.enabled: false` behavior for host should be a quick job.

**Pull request merged**
